apiVersion: apps/v1
kind: Deployment
metadata:
  name: CicdHelloWorld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: CicdHelloWorld
  template:
    metadata:
      labels:
        app: CicdHelloWorld
    spec:
      containers:
        - name: Lambda
          image: amoljohare/cicd_helloword:cicd_helloword
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: CicdHelloWorld
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: CicdHelloWorld